FROM eclipse-temurin:21-jdk AS build

ADD agent-1x/mvnw .
ADD agent-1x/.mvn .mvn

ADD pom.xml .
ADD agent-1x/src agent-1x/src
ADD agent-1x/pom.xml agent-1x/pom.xml

RUN --mount=type=cache,target=/root/.m2 ./mvnw -f agent-1x/pom.xml clean package -DskipTests

FROM eclipse-temurin:21-jre

ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.33.1/opentelemetry-javaagent.jar opentelemetry-javaagent.jar

COPY --from=build /agent-1x/target/agent-one-1.0-SNAPSHOT.jar app.jar

CMD ["java", "-javaagent:opentelemetry-javaagent.jar", "-jar", "app.jar"]
