FROM eclipse-temurin:21-jdk AS build

ADD agent-2x/mvnw .
ADD agent-2x/.mvn .mvn

ADD pom.xml .
ADD agent-2x/src agent-2x/src
ADD agent-2x/pom.xml agent-2x/pom.xml

RUN --mount=type=cache,target=/root/.m2 ./mvnw -f agent-2x/pom.xml clean package -DskipTests

FROM eclipse-temurin:21-jre

ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.2.0/opentelemetry-javaagent.jar opentelemetry-javaagent.jar

COPY --from=build /agent-2x/target/agent-two-1.0-SNAPSHOT.jar app.jar

CMD ["java", "-javaagent:opentelemetry-javaagent.jar", "-jar", "app.jar"]
